# Generated by Django 2.2.4 on 2019-08-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_title', max_length=100, null=True)),
                ('current_group_student_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_group_size', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('current_project_student_count', models.IntegerField(default=0)),
                ('project_code', models.CharField(default='', max_length=15)),
                ('directions', models.TextField(default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('color', models.CharField(default='blue', max_length=100, null=True)),
                ('current_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_current_group_of_the_student', to='users.Group')),
                ('groups', models.ManyToManyField(blank=True, related_name='list_of_groups_that_the_student_is_in', to='users.Group')),
                ('student_projects', models.ManyToManyField(blank=True, related_name='list_of_student_projects_current', to='users.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_associated_with_group', to='users.Project'),
        ),
    ]
